@extends('templates.admin.principal')
@section('content')
    {!!Form::model($user,['route'=>['user.update',$user->id],'method'=>'PUT'])!!}
    @include('user.forms.usr')
    {!!Form::submit('Actualizar',['class'=>'btn-primary'])!!}
    {!!Form::close()!!}
    {!!Form::open(['route'=>['user.destroy',$user->id],'method'=>'DELETE'])!!}
    {!!Form::submit('Eliminar',['class'=>'btn-danger'])!!}
    {!!Form::close()!!}
@stop